# bu dosya sayesinde bu dizinde make foo komutu foo.c dosyasını
# -ansi flagiyle derleyecektir. İsterseniz bu dosyayı silip de 
#  foo.c'yi aynı komutla derleyebilirsiniz. Değişen tek şey aşağıdaki
#  variable'ın -ansi yerine "" değerini alması olacaktır.
CFLAGS = -ansi
